### ISSUE TITLE
hey bro thanks for awesome repo

### ISSUE THREAD

**Issue by halukmy** [ricaun/SimpleLMIC#1]
is it supports class C?

i need contiunisly communication

**Comment by ricaun** [comment]
That's a good question, I believe the current version of the LMIC not support Class C, in the case does not work 😐

**Comment by halukmy** [comment]
@ricaun i can not downlink over gateway is that a problem one single channel how you can downlink esp to this node?

**Comment by ricaun** [comment]
I'm not implemented single channel on the code yet. LoRaWAN is not intended to work with single channel, what gateway are you using?

**Comment by halukmy** [comment]
im using esp32 ttgo lorawan module
https://github.com/vpcola/ESP32SingleChannelGateway 
check this out

you got email?

**Comment by ricaun** [comment]
Maybe is a better library for your case: https://github.com/BeelanMX/Beelan-LoRaWAN

**Comment by halukmy** [comment]
have you support for LoRa E32 TTL ?

**Comment by ricaun** [comment]
Hello, no it's not support the LoRa E32 TTL. 
I'm gonna close de issue, it is loosing the focus.
If you want to talk send a email: ricaun@gmail.com
See yaaa

**Comment by rezaghorbaniii** [comment]
Hi, thanks for the excellent repo.
Do you have any plan To add Class C support?
